// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg7G1xW7WrDa3MaqSHnB3N0cehhw42NqQ',
    appId: '1:425498138977:web:b5a876d30a3ca640450d20',
    messagingSenderId: '425498138977',
    projectId: 'flutter-chatting-app-b8ee6',
    authDomain: 'flutter-chatting-app-b8ee6.firebaseapp.com',
    storageBucket: 'flutter-chatting-app-b8ee6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5JV4DHxgrNEb3YonbvF34AWzekVGzW6c',
    appId: '1:425498138977:android:f6004f6dc836b7f1450d20',
    messagingSenderId: '425498138977',
    projectId: 'flutter-chatting-app-b8ee6',
    storageBucket: 'flutter-chatting-app-b8ee6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi3S8yia5e4CA8UR8cl2AS-BrpUmdfE_0',
    appId: '1:425498138977:ios:065fee49bbe068b6450d20',
    messagingSenderId: '425498138977',
    projectId: 'flutter-chatting-app-b8ee6',
    storageBucket: 'flutter-chatting-app-b8ee6.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi3S8yia5e4CA8UR8cl2AS-BrpUmdfE_0',
    appId: '1:425498138977:ios:065fee49bbe068b6450d20',
    messagingSenderId: '425498138977',
    projectId: 'flutter-chatting-app-b8ee6',
    storageBucket: 'flutter-chatting-app-b8ee6.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg7G1xW7WrDa3MaqSHnB3N0cehhw42NqQ',
    appId: '1:425498138977:web:59bec8eff5426c93450d20',
    messagingSenderId: '425498138977',
    projectId: 'flutter-chatting-app-b8ee6',
    authDomain: 'flutter-chatting-app-b8ee6.firebaseapp.com',
    storageBucket: 'flutter-chatting-app-b8ee6.firebasestorage.app',
  );

}